

### 회원가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jin",
  "age": 28,
  "loginId": "jin123",
  "password": "1234"
}

### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "loginId": "jin123",
  "password": "1234"
}