POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jin",
  "age": 20
}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Steve",
  "age": 20
}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Brian",
  "age": 55
}

###

GET http://localhost:8080/users

###

PUT http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "Steve-update",
  "age": 30
}

###

DELETE http://localhost:8080/users/2

###

GET http://localhost:8080/users